import = ["~/.config/alacritty/themes/solarized_dark.toml"]

live_config_reload = true

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 1

[scrolling]
# auto_scroll = true
# faux_multiplier = 100
history = 2000
multiplier = 20

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 5
y = 5
